#!/usr/bin/env node
import { program } from 'commander'
import geo from './index.js'
import pkg from './package.json' with { type: "json" }
program.version(pkg.version)
	.argument('<domain>', 'Type of object to query')
	.argument('<method>', 'Operation to execute')
	.option('-n, --name', 'List only names')
	.option('-H, --hydrate', 'Hydrate codes to names')
	.option('-c, --criteria <json>', 'Search key or criteria in JSON format')
	.option('-r, --raw', 'Return raw data without processing')
	.parse(process.argv)

const [domain, method] = program.args
const opts = program.opts()
if (!Object.hasOwn(geo, domain) || !['keys', 'meta', 'list', 'find'].includes(method)) {
    program.error('Unknown domain or method')
}
if (opts.criteria) {
    try {
        opts.criteria = JSON.parse(opts.criteria)
    } catch {
        if (/^[\[{"]/.test(opts.criteria)) program.error('Invalid JSON criteria')
        // Unquoted keys such as US are also accepted.
    }
}
var res
try {
    res = geo[domain][method](opts)
} catch (error) {
    program.error(error.message)
}
console.log(JSON.stringify(res, null, 2))
